[package]
name = "regioned"
version = "1.0.0"
edition = "2021"

[features]
dot = []

[dependencies]
tinyvec = { version = "=1.6.0", features = ["alloc"] }

[dependencies.arena]
git = "https://github.com/Rerumu/Arena"
rev = "db2f439"

[dev-dependencies]
criterion = "=0.4.0"

[[bench]]
name = "basic"
harness = false
